### ISSUE TITLE
Service broker rejected the request

### ISSUE THREAD

**Issue by Omnipresent** [cloudfoundry-incubator/local-volume-release#2]
I have a need  for my application hosted on CF to access a shared volume. For this reason I wanted to try out this release. I have bosh-lite installed on my mac with following releases

When i try to `create-service` I get this error

```
➜  ~ cf create-service-broker localbroker admin admin http://localbroker.bosh-lite.com
Creating service broker localbroker as admin...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker rejected the request to http://localbroker.bosh-lite.com/v2/catalog. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('localbroker.bosh-lite.com') does not exist.
```

For my usecase at the moment, I'm simply trying to mount a folder on my mac like `/Users/omni/somefolder` to my application so that it can access files residing in that folder.

**Comment by julian-hj** [comment]
A couple quick questions:
Is this a new bosh-lite installation? Are you able to push apps to it and access them? If not maybe you need to run add-routes from the bosh-lite folder on your Mac. 

Assuming that your bosh lite is ok, the next step would be to check to make sure the broker is running. What do you see when you run `bosh deployments`?

If the local deployment is there and running then probably you will want to bosh ssh to the local broker vm and check to make sure that local broker and route registrar are both running.

**Comment by julian-hj** [comment]
Closing this issue as we have picked up the thread on [slack](https://cloudfoundry.slack.com/messages/persi/).  Feel free to reach out here or on slack again if you need any further assistance.
